# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        our_db_provider:
            entity:
                class: AppBundle:User
                property: name

#        in_memory:
#            memory:
#                users:
#                    umakant:
#                        password: umakant
#                        roles: 'ROLE_USER'
#
#                    faruk:
#                        password: umakant
#                        roles: 'ROLE_ADMIN'

    encoders:
        AppBundle\Entity\User: plaintext
        Symfony\Component\Security\Core\User\User: plaintext

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            # activate different ways to authenticate
#            pattern: ^/
            http_basic: ~
            provider: our_db_provider
            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            form_login:
                 login_path: login
                 check_path: login
                 default_target_path: /User/
                 failure_path: login
#             http://symfony.com/doc/current/cookbook/security/form_login_setup.html
#        secured_area:
#            # ...
            logout:
                path: /logout
                target: /login
    access_control:
    - { path: ^/Login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/Register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/User/, roles: IS_AUTHENTICATED_FULLY }
    - { path: ^/User/Event/Update/, roles: IS_AUTHENTICATED_FULLY }
    - { path: ^/User/Event/, roles: IS_AUTHENTICATED_FULLY }
